inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snippets from READMEs.
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'bin/*'

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  Max: 4

Metrics/BlockLength:
  Exclude:
    - 'app/admin/*.rb'
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: true

RSpec/MultipleExpectations:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Enabled: false
